django-project/Accounts/urls.py
from django.urls import path
from .views import *
from .checkinregister import *

app_name='accounts'

urlpatterns=[

    path('register',UserRegisteView.as_view(),name='register'),
    path('check/email/',check.as_view(),name='emailexist'),
    path('check/phone/',CheckPhone.as_view(),name='checkphone'),
    path('check/username/',CheckUsername.as_view(),name='checkusername'),
    path('verifycode',OtpCodeView.as_view(),name='verifycode'),
    path('login',LoginView.as_view(),name='login'),
    path('logout',LogoutView.as_view(),name='logout'),
    path('profie',UserProfileView.as_view(),name='profile'),
    path('notification',NotifacationView.as_view(),name='notification'),
    path('company/sumbit/',CompanyView.as_view(),name='company'),
    path('company/verify/',CopmanyVerifyView.as_view(),name='company_verify'),
    path('notifications/',NotificationsView.as_view(),name='notifications'),
    


  


    #resetpassword
    path('password/reset/',PasswordResetView.as_view(),name='passwordreset'),
    path('password/reset/done',PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password/reset/confirm/<uidb64>/<token>/',PasswordResetConfirm.as_view(),name='password_reset_confirm'),
    path('password/reset/complate',PasswordResetComplateView.as_view(),name='password_reset_complate'),
    

   

    


]

django-project/HasanAbad/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('Accounts.urls',namespace='accounts')),
    path('category/',include('category.urls',namespace='category')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

django-project/Accounts/models.py
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from .manager import MyUserManager


# Create your models here.

class User(AbstractBaseUser):
    email = models.EmailField(max_length=200,unique=True)
    username = models.CharField(max_length=50,unique=True)
    phone = models.CharField(max_length=13)
    address = models.CharField(max_length=500,blank=True)
    name =  models.CharField(max_length=50)
    family =  models.CharField(max_length=50)
    poster = models.ImageField(upload_to='poster/')
    is_superuser = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    objects = MyUserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS =('username','phone')

    def __str__(self) -> str:
        return self.email
    
    def has_perm(self,perm,obj=None):
        return True
    
    def has_module_perms(self,app_label):
        return True
    
    @property
    def is_staff(self):
        return self.is_admin




class CompanyModel(models.Model):
    user = models.OneToOneField(User,models.CASCADE,related_name='cuser')
    name = models.CharField(max_length=20,null=True)
    national_card = models.ImageField()
    business_license = models.ImageField()
    verify = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user} ------- is admin' 
        
    # def save(self,*args,**kwargs):
    #     self.verify =True
    #     return super().save(*args,**kwargs)
    #     with open(f'{self.user}/nationalcode',)
        

class OtpCodeModel(models.Model):
    phone = models.CharField(max_length=13)
    code = models.IntegerField(null=True)
    created = models.DateTimeField(auto_now_add=True)

from category.models import OrderModel

class NotifacationModel(models.Model):
    user = models.ForeignKey(User,models.CASCADE,related_name='usernoti')
    text = models.CharField(max_length=500,null=True)
    view = models.BooleanField(default=False)


    

django-project/Accounts/forms.py
from dataclasses import field, fields
from pyexpat import model
from django import forms
from .models import CompanyModel, OtpCodeModel, User
from django.contrib.auth.forms import ReadOnlyPasswordHashField

class UsercreateForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email','phone','username')
    
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 !=password2:
            raise forms.ValidationError('password not math')
        if len(password2) < 7:
            raise forms.ValidationError('password not 8 ')

        return password1
    


    def save(self, commit= False):

        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user
    



class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = []


class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50)
    
class CompanyForm(forms.ModelForm):
    class Meta:
        model = CompanyModel
        fields = ('national_card','business_license')
        

django-project/Accounts/views.py
import json
from secrets import choice
from unicodedata import name
from django.contrib import messages
from django.conf import settings
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render ,redirect
from django.views import View
from category.models import OrderModel
from .forms import UsercreateForm,UserLoginForm,CompanyForm
from django.contrib.auth import views as auth_view
from .models import CompanyModel, User , OtpCodeModel,NotifacationModel
from random import randint
from django.core.mail import send_mail
from django.contrib.auth import login,logout,authenticate
from django.urls import reverse_lazy
import string
from comment.models import CommentModel, ReplayCommentModel



# Create your views here.


class UserRegisteView(View):
    def get(Self,request):
        return render(request,'accounts/user_register2.html')
    
    def post(self,request):

        form = UsercreateForm(request.POST)

        if form.is_valid():

            
            cd = form.cleaned_data
            email = cd['email']
            phone = cd['phone']
            password = cd['password1']
            username = cd['username']
            
            code = randint(10000,99999)
            otp_exist=OtpCodeModel.objects.filter(phone=phone)
            if otp_exist is not None:
                otp_exist.delete()
            OtpCodeModel.objects.create(phone=phone,code=code)
            send_mail('verify code',str(code),settings.EMAIL_HOST_USER,(email,))
            messages.success(request,'ایمیل حاوی کد تایید برای شما ارسال شد','success')
            
            request.session['userinfo'] = {
                'email':email,
                'phone':phone,
                'password':password,
                'username':username,
            }
                      
            return redirect('accounts:verifycode')
       

        messages.success(request,'لطفا مقادیر را بررسی کنید','info')
         
        return render(request,'accounts/user_register2.html',{'form':form})

class OtpCodeView(View):
    def get(self,request):
        phone , email=  request.session['userinfo']['phone'],request.session['userinfo']['email']
        return render(request,'accounts/user_verfy.html',{'phone':phone,'email':email})
    
    def post(self,request):
        info = request.session['userinfo']
        code = request.POST['code']
        otp = OtpCodeModel.objects.get(phone = info['phone'])
      
        if (str(otp.code) == str(code)):
            User.objects.create_user(username = info['username'] , email = info['email'],phone = info['phone'],password = info['password'])
            otp.delete()
            return redirect('accounts:login')

        else:
            messages.info(request,'کد نامعتبر می باشد ','info')
            return redirect('accounts:verifycode')


class LoginView(View):
    def get(self,request):
        
        return render(request,'accounts/login.html')
    
    def post(self,request):
        
        form =UserLoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            username = cd['username']
            password = cd['password']
            user = authenticate(request,email=username , password=password)
            if user is not None:
                login(request,user)
                messages.success(request,'شما با موفقیت وارد شدید','success')
                return redirect('category:category')
            else:
                messages.info(request,'رمز عبور یا نام کاربری اشتباه است','info')
                return redirect('accounts:login')
        else:
            messages.info(request,'عملیات با خطا مواجه شد','info')
            return redirect('accounts:login')
        

class LogoutView(View):
    def get(self ,request):
        logout(request)
        messages.success(request,'شما با موفقیت خارج شدید','success')
        return redirect('accounts:login')





class PasswordResetView(auth_view.PasswordResetView):
    template_name = 'accounts/reset/password_reset.html'
    email_template_name = 'accounts/reset/email.html'
    success_url=reverse_lazy('accounts:password_reset_done')

class PasswordResetDoneView(auth_view.PasswordResetDoneView):
    template_name = 'accounts/reset/password_reset_done.html'


class PasswordResetConfirm(auth_view.PasswordResetConfirmView):
    template_name='accounts/reset/password_reset_confirm.html'
    success_url=reverse_lazy('accounts:password_reset_complate')
    
    

class PasswordResetComplateView(auth_view.PasswordResetCompleteView):
    template_name = 'accounts/reset/password_reset_complate.html'


class UserProfileView(View):
    def get(self,request):
        
        return render(request,'accounts/profile.html')
    
    def post(self,request):
        
        info = request.POST
        user = User.objects.get(id = request.user.id)
        user.email = request.user.email
        user.phone = request.user.phone
        user.name = info['name']
        user.family = info['family']
        user.address = info['address']
        user.save()
        if request.GET.get('next') =='orderview':
            return redirect('category:order')
        return redirect('category:category')
class NotifacationView(View):
    def get(self,request):
        myorders = OrderModel.objects.filter(usersender=request.user,view=False)
        # for order in myorders:
        #     order.view = True
        #     order.save
        return render(request,'accounts/noti.html',{'myorders':myorders})
    def post(self,request):
        idorder = request.POST.get('idorder')
        iduser = request.POST.get('iduser')



from django.core.files.storage import FileSystemStorage
def password():
    char = string.ascii_letters + string.punctuation + string.digits
    passcode = ''.join(choice(char) for x in range(randint(8,16)))
    return passcode


class CompanyView(View):
   

    def get(self,request):
        return render(request,'accounts/company.html')

    def post(self,request):
        user = request.user
        national_card = request.FILES.get('national_card')
        national_card_fss = FileSystemStorage()
        national_card_file = national_card_fss.save(f'company/{request.user.username}/national_card{password()}.jpg',national_card)
        national_card_url = national_card_fss.url(national_card_file)
       
        business_license = request.FILES.get('business_license')
        business_license_fss = FileSystemStorage()
        business_license_file = business_license_fss.save(f'company/{request.user.username}/business_license{password()}.jpg',business_license)
        business_license_url = business_license_fss.url(business_license_file)
        namecompany = request.POST.get('namecompany')
       
        try:
            CompanyModel.objects.create(user = user,national_card=national_card_url,business_license=business_license_url,name = namecompany)
            messages.success(request,'درخواست شما ثبت شد و بس از تایید شما قادر به افزودن کالا در سایت می باشید')
            return redirect('accounts:company')
        except:
            messages.success(request,'مشکلی به وجود امده است یا شما قبلا در سایت ثبت نام کرده اید ')
            return redirect('accounts:company')


class CopmanyVerifyView(View):
    email_text = 'شرکت شما در سایت ثبت شده است و شما قادر میباشید تا آگهی ثبت و سفارشات را دریافت نمایید'
    def get(self,request):
        companies = CompanyModel.objects.filter(verify = False)
        return render(request,'accounts/company_verify.html',{'companies':companies})

    def post(self,request):
        id = request.POST['id']
        company = CompanyModel.objects.get(id = id)
        company.verify = True
        company.save()
        user = User.objects.get(id = company.user.id)
        user.is_admin= True
        
        user.save()
        send_mail('تاییذیه شرکت شما ',self.email_text,settings.EMAIL_HOST_USER,(company.user.email,))
        messages.success(request,'شرکت ثبت شد','success')
        return JsonResponse({'status':'ok'})


class NotificationsView(View):
    def get(self,request):
        comments = ReplayCommentModel.objects.filter(to_user = request.user.username,view=False)
        comments_tag = CommentModel.objects.filter(to_user = request.user.username)
        comments_view = ReplayCommentModel.objects.filter(to_user = request.user.username,view=True)
        return render(request,'accounts/notifications.html',{'comments':comments,'comments_view':comments_view,'comments_tag':comments_tag})
    
    def post(self,request):
        comments = ReplayCommentModel.objects.filter(to_user = request.user.username)
        for c in comments:
            c.view =True
            c.save()
        return JsonResponse({'status':'ok'})

django-project/Accounts/templates/accounts/reset/email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

django-project/Accounts/templates/accounts/reset/password_reset.html
{% extends 'base.html' %}

{% block css %}
    <link rel="stylesheet" href="" 
{% endblock %}
{% block title %}
    user login
{% endblock %}
{% block body %}

<div class="container">
    <div class="row">
      
        <form method="post" action="" class="col-md-4 bg-dark mt-2 mx-auto">
         
            <div class="mb-3">
            <label for="exampleInputPassword1" class="form-text mb-2">ایمیل :</label>
            <input type="email" class="form-control" dir="ltr" placeholder="example.gmail.com" name="email" id="email" >
            </div>
           
            {% csrf_token %}
                
                    <div class="mx-auto m-2 col-md-12 text-center" >
                     <button type="submit"  class="col-md-12 btn btn-secondary mb-2">تایید</button>
                  
                    
                 
                  
               
                  
           
        </form>
    </div>

    </div>
{% endblock %}

{% block script %}

<script src="/static/accounts/js/accountsjs.js"></script>

{% endblock %}

django-project/Accounts/templates/accounts/reset/password_reset_complate.html
{% extends 'base.html' %}

{% block css %}
    <link rel="stylesheet" href="" 
{% endblock %}
{% block title %}
    verify code 
{% endblock %}
{% block body %}

<div class="container">
    <div class="row">
        <p  class="alert alert-info">رمز عبور با موفقیت تفییر یافت</p>
      
        
    </div>
{% endblock %}

{% block script %}

<script>
    var button = document.getElementById('register')
    button.classList.add('active')
</script>
{% endblock %}

django-project/Accounts/templates/accounts/reset/password_reset_confirm.html
{% extends 'base.html' %}

{% block css %}
    <link rel="stylesheet" href="" 
{% endblock %}
{% block title %}
    user login
{% endblock %}
{% block body %}

<div class="container">
    <div class="row">
      
        <form method="post" action="" class="col-md-4 bg-dark mt-2 mx-auto">
         
             <!-- {{form}} -->
            <div class="mb-3">
            <label for="exampleInputPassword1" class="form-text mb-2">رمز عبور جدید :</label>
            <input type="password" class="form-control" dir="ltr" placeholder="password" name="new_password1" id="new_password1" >
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-text mb-2">تکرار رمز عبور جدید :</label>
                <input type="password" class="form-control" dir="ltr" placeholder="new_password" name="new_password2" id="new_password2" >
                </div>
           
            {% csrf_token %}
                
                    <div class="mx-auto m-2 col-md-12 text-center" >
                     <button type="submit"  class="col-md-12 btn btn-secondary mb-2">تایید</button>
                  
                    
                 
                  
                
                  
           
        </form>
    </div>

    </div>
{% endblock %}

{% block script %}

<script src="/static/accounts/js/accountsjs.js"></script>

{% endblock %}

django-project/Accounts/templates/accounts/reset/password_reset_done.html
{% extends 'base.html' %}

{% block css %}
    <link rel="stylesheet" href="" 
{% endblock %}
{% block title %}
    verify code 
{% endblock %}
{% block body %}

<div class="container">
    <div class="row">
        <p  class="alert alert-info">ایمیل ارسال شد</p>
      
        
    </div>
{% endblock %}

{% block script %}

<script>
    var button = document.getElementById('register')
    button.classList.add('active')
</script>
{% endblock %}