django-project/Accounts/urls.py
from django.urls import path
from .views import *
from .checkinregister import *

app_name='accounts'

urlpatterns=[

    path('register',UserRegisteView.as_view(),name='register'),
    path('check/email/',check.as_view(),name='emailexist'),
    path('check/phone/',CheckPhone.as_view(),name='checkphone'),
    path('check/username/',CheckUsername.as_view(),name='checkusername'),
    path('verifycode',OtpCodeView.as_view(),name='verifycode'),
    path('login',LoginView.as_view(),name='login'),
    path('logout',LogoutView.as_view(),name='logout'),
    path('profie',UserProfileView.as_view(),name='profile'),
    path('notification',NotifacationView.as_view(),name='notification'),
    path('company/sumbit/',CompanyView.as_view(),name='company'),
    path('company/verify/',CopmanyVerifyView.as_view(),name='company_verify'),
    path('notifications/',NotificationsView.as_view(),name='notifications'),
    


  


    #resetpassword
    path('password/reset/',PasswordResetView.as_view(),name='passwordreset'),
    path('password/reset/done',PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password/reset/confirm/<uidb64>/<token>/',PasswordResetConfirm.as_view(),name='password_reset_confirm'),
    path('password/reset/complate',PasswordResetComplateView.as_view(),name='password_reset_complate'),
    

   

    


]

django-project/HasanAbad/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('Accounts.urls',namespace='accounts')),
    path('category/',include('category.urls',namespace='category')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

django-project/category/urls.py
from operator import ne
from django.urls import path
from .views import *
from .send_email import SendEmailView
app_name='category'

urlpatterns=[
    path('',CategoryView.as_view(),name='category'),

    # path('/<str:strproduct>/',CategoryView.as_view(),name='category'),
    # path('cat/<str:strproduct>',SearchView2.as_view(),name='searc'),
    
    path('add',AddProductView.as_view(),name='addproduct'),
    path('cart/',CartView.as_view(),name='cart'),
    path('card/add/',CartAddView.as_view(),name='cartadd'),
    path('card/remove/',CartRemoveView.as_view(),name='cartremove'),

    path('order/',OrderView.as_view(),name='order'),
    path('sendorder/',SendOrderView.as_view(),name='sendorder'),
    path('sendorder/submit/',SubmitOrderView.as_view(),name='submitorder'),
    path('oldorders/',OldOrderView.as_view(),name='oldorders'),
    path('sendorderuser/',SendOrderUserView.as_view(),name='sendorderuser'),
    path('sendorder/back/',BackOrderView.as_view(),name='backorder'),
    path('commentadd/',CommentAddView.as_view(),name='comment'),
    path('search/<str:strproduct>',SearchView.as_view(),name='search'),
    # path('<slug:slug>/<slug:brand_slug>',SearchView.as_view(),name='search_type'),
    path('like/',LikeView.as_view(),name='like'),
    path('send/email/user/',SendEmailView.as_view(),name='sendemail'),

    path('cat/choise/',ChoiseView.as_view(),name='choise'),
    path('details/product/<str:cat_slug>/<str:brand_slug>/<str:product_slug>',ProductDetailsView.as_view(),name='datails'),
    path('addstar/',StarAddView.as_view(),name="addstar"),
    path('sharepost/',SharePostView.as_view(),name="addstar"),


    




    ]

django-project/templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{msg.tags}}">{{msg}}</p>
    {% endfor %}
{% endif%}

django-project/templates/inc/navbar.html
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark mt-2">
    <div class="container-fluid">
      
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse " id="navbarColor01">
        <ul class="navbar-nav me-auto mx-auto mb-2 mb-lg-0">
            {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a id="home" class="nav-link " aria-current="page" href="{% url 'category:category'%}">صفحه اصلی</a>
          </li>
          <a href="{% url 'accounts:notifications' %}"  class="nav-link position-relative">
             اعلان
            <span class="position-absolute top-10 start-0 translate-middle badge rounded-pill bg-danger">
            {{lenorders}}
              <span class="visually-hidden">unread messages</span>
            </span>
            </a>
              </li>
        
          <li class="nav-item">
            <a class="nav-link" href="#">مشخصات</a>
          </li>
            {% if request.user.is_admin == False %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:company' %}">ثبت کسب و کار و مغازه</a>
          </li>
          {% endif %}
          
             {% else %}
          <li class="nav-item">
            <a id="register" class="nav-link" href="{% url 'accounts:register' %}">ثبت نام</a>
          </li>
          <li class="nav-item">
            <a id="login" class="nav-link" href="{% url 'accounts:login' %}">ورود</a>
          </li>
             {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'category:cart' %}">سبد خرید</a>
          </li>
          
         
          <li class="nav-item">
            <a class="nav-link" href="#">ارتباط با ما</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">خروج</a>
          </li>
          {% endif %}
          {% if request.user.is_admin %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'category:addproduct'%}">ثبت آگهی</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'category:sendorder' %}">سفارشات</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'category:oldorders' %}">بایگانی سفارشات</a>
          </li>
          {% if request.user.is_superuser%}
        
         
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:company_verify' %}">شرکت ها </a>
          </li>
          <li class="nav-item">
           
          <a href="{% url 'accounts:notification' %}"  class="nav-link position-relative">
        سفارشات من
        <span class="position-absolute top-10 start-0 translate-middle badge rounded-pill bg-danger">
        {{lenorders}}
          <span class="visually-hidden">unread messages</span>
        </span>
          </a>
          </li>
          {% endif %}
          {% endif %}

        </ul>
       
      </div>
    </div>
  </nav>

 
<style>
  
</style>

django-project/templates/inc/navbar2.html
<header>
    <nav>
        <div onclick=""  class="nav-right">
            {% if user.is_authenticated %}
                <a href="{% url 'accounts:profile' %}">
                    <i class="fa fa-user night"></i>
                    <i id="helptext" class="night">  بروفایل  </i>
               </a>

            {% endif %}
          {% if categories %}
            <a class="product active_nav">
                 <i id="list_nav"  class=" fa fa-list night"></i>
                <i class="night" id="helptext">  محصولات </i>
                <div class="search-box">
                    <div class="row search-box-body">
            {% for category in categories %}
            <div class="box-search col-lg-3 col-md-4 col-sm-6 col-xs-12">
                <h6 class="product-title-menu">{{category.name_category}}</h6>
                    <ul>
                        {% for typeproduct in category.type.all %}
                            <li onclick="itemclick(this)" data-slug="{{typeproduct.slug}}">{{typeproduct.name}}</li>
                        {% endfor %}
    
                    </ul>
                </div>
               {% endfor %}
                
                           
                    
                    </div>
                </div>
                
            
            </a>
            {% endif %}
           <a  href="{% url 'category:cart' %}">
            
             <i id="cart_nav" class="fa fa-shopping-cart night"></i>
            <i class="night" id="helptext"> سبد </i>

        </a>
       

           <a href="{% url 'category:category'%}"> <i id="home_nav" class="fa fa-home night"></i>
            <i class="night" id="helptext"> فروشگاه </i>

        </a>
           <a id="searchbtn" class="searchbtn" > <i id="simple_search" onclick="searchclick()" class="fas fa-search search night">
            

        </i>
        <i class="night" id="helptext"> جستجو </i>
    
    </a>
           <input onsubmit="searchclick()"  class="inputsearch" id="inputsearch" type="text">
           {% if request.user.is_admin %}
           <a href=""> <i class="fa fa-add night"></i>
            <i class="night" id="helptext"> افزودن </i>
        
        </a>
        {% endif %}
        {% if home %}
           <a href="{% url 'accounts:company' %}" class="insta"> 
            <i class="fa fa-university" aria-hidden="true"></i>
            <i class="night"  id="helptext">مشارکت</i>
        
        </a>

           <a> <i data-mode="night" id="night_mode" onclick="night_mode_click(this)" class="fa fa-moon night"></i>
            <i  class="night help_night"  id="helptext">  شب </i>
        
        </a>
        {% endif %}

    
       



        </div>
        <div class="nav-left ">
            
            <div class="login-register-btn">
                {% if user.is_authenticated == False %}
                    <i  class="far fa-user night"></i>
                    <a class="night"  href="{% url 'accounts:login' %}">ثبت نام/ ورود</a>
                {% else %}
                    <i  class="fa fa-close night"></i>
                    <a class="night"  href="{% url 'accounts:logout' %}"> خروج</a>
                {% endif %}
            </div>
            
            
        </div>
       
       

    </nav>
    
</header>
<script>

</script>