django-project/Accounts/urls.py
from django.urls import path
from .views import *
from .checkinregister import *

app_name='accounts'

urlpatterns=[

    path('register',UserRegisteView.as_view(),name='register'),
    path('check/email/',check.as_view(),name='emailexist'),
    path('check/phone/',CheckPhone.as_view(),name='checkphone'),
    path('check/username/',CheckUsername.as_view(),name='checkusername'),
    path('verifycode',OtpCodeView.as_view(),name='verifycode'),
    path('login',LoginView.as_view(),name='login'),
    path('logout',LogoutView.as_view(),name='logout'),
    path('profie',UserProfileView.as_view(),name='profile'),
    path('notification',NotifacationView.as_view(),name='notification'),
    path('company/sumbit/',CompanyView.as_view(),name='company'),
    path('company/verify/',CopmanyVerifyView.as_view(),name='company_verify'),
    path('notifications/',NotificationsView.as_view(),name='notifications'),
    


  


    #resetpassword
    path('password/reset/',PasswordResetView.as_view(),name='passwordreset'),
    path('password/reset/done',PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password/reset/confirm/<uidb64>/<token>/',PasswordResetConfirm.as_view(),name='password_reset_confirm'),
    path('password/reset/complate',PasswordResetComplateView.as_view(),name='password_reset_complate'),
    

   

    


]

django-project/HasanAbad/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('Accounts.urls',namespace='accounts')),
    path('category/',include('category.urls',namespace='category')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

django-project/category/urls.py
from operator import ne
from django.urls import path
from .views import *
from .send_email import SendEmailView
app_name='category'

urlpatterns=[
    path('',CategoryView.as_view(),name='category'),

    # path('/<str:strproduct>/',CategoryView.as_view(),name='category'),
    # path('cat/<str:strproduct>',SearchView2.as_view(),name='searc'),
    
    path('add',AddProductView.as_view(),name='addproduct'),
    path('cart/',CartView.as_view(),name='cart'),
    path('card/add/',CartAddView.as_view(),name='cartadd'),
    path('card/remove/',CartRemoveView.as_view(),name='cartremove'),

    path('order/',OrderView.as_view(),name='order'),
    path('sendorder/',SendOrderView.as_view(),name='sendorder'),
    path('sendorder/submit/',SubmitOrderView.as_view(),name='submitorder'),
    path('oldorders/',OldOrderView.as_view(),name='oldorders'),
    path('sendorderuser/',SendOrderUserView.as_view(),name='sendorderuser'),
    path('sendorder/back/',BackOrderView.as_view(),name='backorder'),
    path('commentadd/',CommentAddView.as_view(),name='comment'),
    path('search/<str:strproduct>',SearchView.as_view(),name='search'),
    # path('<slug:slug>/<slug:brand_slug>',SearchView.as_view(),name='search_type'),
    path('like/',LikeView.as_view(),name='like'),
    path('send/email/user/',SendEmailView.as_view(),name='sendemail'),

    path('cat/choise/',ChoiseView.as_view(),name='choise'),
    path('details/product/<str:cat_slug>/<str:brand_slug>/<str:product_slug>',ProductDetailsView.as_view(),name='datails'),
    path('addstar/',StarAddView.as_view(),name="addstar"),
    path('sharepost/',SharePostView.as_view(),name="addstar"),


    




    ]

django-project/category/forms.py
from django import forms
from .models import ProductModel

class AddProductForm(forms.ModelForm):
    class Meta:
        model=ProductModel
        fields = ('name','des','price')

django-project/category/views.py
from itertools import count
import json
from multiprocessing.pool import AsyncResult
from operator import length_hint
from os import lstat
import re
import string
from typing import List

from django import views
import django
from django.http import HttpRequest, HttpResponse, JsonResponse, QueryDict
from django.shortcuts import redirect, render
from django.urls import reverse_lazy ,reverse
from django.views import View
from .models import *
from .forms import AddProductForm 
from django.core.files.base import ContentFile
from django.utils.text import slugify
from .cart import Cart
from Accounts.views import UserProfileView
from django.contrib import messages
from comment.models import CommentModel,ReplayCommentModel
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .send_email import send_email
from .utils import shopping_cart


# Create your views here.

class CategoryView(View):
    def get(self,request):
        buys = []
        

        if request.session.get('cart') is not None:
            buys = shopping_cart(request)
        most_like_product = ProductModel.objects.filter(like_count__gt =4)
        # products = []
        
        # x=0
        # for product in most_like_product:
        #     if (int(product.star)) >= 4:
        #         products.append(product)
        #         x +=1
        #         if x == 7:
        #             return
        

        # most_like_product = products
        home=True
        categories = CategoryModel.objects.all()
        return render(request,'category/home.html',{'home':home,'most_like_product':most_like_product,'categories':categories,'buys':buys})

# class SearchView2(View):
#     def get(self,request,strproduct):
#         type = TypeProductModel.objects.get(slug=strproduct)
#         product = ProductModel.objects.filter(type=type).values()

#         product = list(product)
#         return JsonResponse(product,safe=False)
class AddProductView(LoginRequiredMixin,View):
    def get(self,request):
        category = CategoryModel.objects.all()
        brands = BrandModel.objects.all()
        return render(request,'category/add_product.html',{'category':category,'brands':brands})
    
    def post(self,request):
        form =AddProductForm(request.POST)
        category = CategoryModel.objects.get(name_category=request.POST['category'])
        brand = BrandModel.objects.get(category=category,name_brand = request.POST['brand'])
        
       
        if form.is_valid():
            cd = form.cleaned_data
            product = ProductModel.objects.create(user =request.user,name=cd['name'], category=category,brand=brand,des=cd['des'],price=cd['price'])
            product.slug=slugify(f'{product.id}-{product.name}')
            
            product.save()
            
        file = request.FILES.getlist("images[]")
        
        for img in file:
            ImageProductModel.objects.create(product=product,image=img)
            
        return HttpResponse("yes")
        
       

class ProductDetailsView(View):
    def get(self,request,product_slug,*args,**kwargs):
        print(product_slug)
        product = ProductModel.objects.get(slug=product_slug)
        # print('9'*90)
        # product.star[15]=71
        # product.save()
        # print((product.star.keys()))
        comment = CommentModel.objects.filter(product = product,is_replay=False)
        images = ImageProductModel.objects.filter(product=product)
        print(comment)
        # comment_replay = ReplayCommentModel.objects.filter(comment = comment)
        
        return render(request,'category/details_product.html',{'product':product,'comment':comment,'images':images})



class CartView(View):
    def get(self,request):
        cart = Cart(request)
        return render(request,'category/cart2.html',{'cart':cart})
       
class CartAddView(View):
    def post(self,request):
        cart = Cart(request)
        
        product = ProductModel.objects.get(slug=request.POST.get('slug'))
        number = request.POST['number']
        cart = Cart(request)
       

        try:
            if number !="":
                number = int(number)
            else:
                number = 1
            cart.Add(product,number)

            return JsonResponse({'status':'ok','cart_value':request.session['cart']})

        except:
            return JsonResponse({'status':'err'})
        
class CartRemoveView(View):
    def post(self,request):
        product = ProductModel.objects.get(id=request.POST['id'])
        cart = Cart(request)
        cart.Remove(product)
        return JsonResponse({'status':'ok'})


class OrderView(LoginRequiredMixin,View):
    def get(self,request):
        a=OrderModel.objects.filter(user = request.user)
        if request.user.address =='':
            messages.info(request,'برای ثبت سفارش لطفا اطلاعات خود را وارد نمایید','info')
            return redirect('/accounts/profie?next=orderview')
        
        order_create = OrderModel.objects.create(user = request.user,address = request.user.address,phone=request.user.phone,name=f'{request.user.name}{request.user.family}')
        cart = Cart(request)
        
        global  OrderItems
        my_lst=[]
        for order in cart:
            pruduct = ProductModel.objects.get(id=order['product'].id)
            
            my_lst.append(order['product'].user.id)
            OrderItems =  OrderItemsModel.objects.create(order = order_create,user_created =  order['product'].user ,product=pruduct,price=int(order['product'].price),number=int(order['number']))
        #در اینجا باید کاربر به صفحه پرداخت هدایت شود
        del request.session['cart']
        request.session.modified = True
        my_set = set(my_lst)
        for id in my_set:
           
            user = User.objects.get(id=id)
            for order in cart:
                if order['product'].user.id == user.id:
                    ProductNotModels.objects.create(user = user,product=order['product'])
        return HttpResponse(my_lst)


        
    
    
        
class SendOrderView(View):
    def get(self,request):
        if request.user.is_superuser:
            users = User.objects.filter(is_admin=True)
            orders = OrderModel.objects.filter(usersender=None,view=False)
            return render(request,'category/send_order.html',{'orders':orders,'users':users})

        if request.user.is_admin:
            user = User.objects.get(id = request.user.id)
            notification =  OrderItemsModel.objects.filter(user_created = user)       
            noti_view = notification.filter(view=True).order_by('order')
            noti_not_view = notification.filter(view=False)
             
            print(noti_not_view.exists())
        
            my_lst=[]
            for n in notification:
                my_lst.append(n.order.id)
                
            my_set=set(my_lst)
            
            return render(request,'category/not_product.html',{'noti_view':noti_view,'noti_not_view':noti_not_view,'order_id':my_set})

    def post(self,request):
        id = request.POST['id']
        
        notification =  OrderItemsModel.objects.get(id= id)     
        notification.view=True
        notification.save()
        order = OrderModel.objects.get(id = notification.order.id)
        items = OrderItemsModel.objects.filter(order= order)
        my_lst=[]
        all_from_user=1
        for o in items:
            my_lst.append(o.product.name)
            if o.user_created != request.user:
                all_from_user=0
            if o.view == False:
                return
        try:
            send_email(my_lst,order.id,order.user.email,order.address,order.user.name,order.user.family)
            if all_from_user == 1:
                order.usersender=request.user

        except:
            notification.view=False
            notification.save()
            return JsonResponse({'status':'not_net'})
        
        
        order.view = True
        order.save()
            
        
        
        send_email(my_lst,order.id,order.user.email,order.address,order.user.name,order.user.family)
        return JsonResponse({'status':'ok','all':all_from_user})
      


class OldOrderView(View):
    def get(self,request):
        if request.user.is_superuser:
            orders = OrderModel.objects.filter(view=True)
            return render(request,'category/old_orders.html',{'orders':orders})
        else:
            orders = OrderModel.objects.filter(usersender=request.user)
            return render(request,'category/old_orders.html',{'orders':orders})


class SubmitOrderView(View):
    def post(self,request):
        orderid = request.POST.get('id')
        order = OrderModel.objects.get(id = orderid)
        order.view=True
        order.save()
        messages.success(request,'سبد خرید تایید شد','success')
        return JsonResponse({'status':'ok'})
        


class BackOrderView(View):
    def post(self,request):
        orderid = request.POST.get('id')
        order = OrderModel.objects.get(id = orderid)
        order.usersender=None
        order.save()
        messages.success(request,'سبد خرید برگشت داده شد','success')
        return JsonResponse({'status':'ok'})



class SendOrderUserView(View):
    def post(self,request):
        iduser = request.POST.get('iduser')
        idorder = request.POST.get('idorder')
        user = User.objects.get(id = iduser)
        order = OrderModel.objects.get(id = idorder )
        order.usersender = user
        order.save()
        messages.success(request,'سبد خرید تایید شد','success')
        return JsonResponse({'status':'ok'})


class CommentAddView(View):
    def post(self,request):
        id = request.POST.get('id')
        commentbody = request.POST.get('comment')
        productid = request.POST.get('productid')

django-project/category/templates/category/add_product.html
{% extends 'base.html' %}

{% block title %}
    category
{% endblock %}

  
    {% block body %} 
    <div class="container">
        <div class="row">
          
            <form  method="post" action="" enctype="multipart/form-data" class="col-md-4 bg-dark mt-2 mx-auto">
             
            
                
                <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-text mb-2">نام محصول :</label>
                    <input   type="text" class="form-control" dir="rtl" placeholder="لب تاپ ایسوس" name="name" id="name">
                </div>
                <div class="mb-3">
                    <select name="category" onchange="ch()" id="select"   dir="ltr" class="form-select" aria-label="Default select example">
                        <option  selected>انتخاب نوع محصول</option>
                        {% for cat in category %}
                            <option  id="category" value="{{cat}}" >{{cat}}</option>

                        {% endfor %}
                        
                    </select>
                </div>
                <div class="mb-3">
                    <select name="brand" id="option"   dir="ltr" class="form-select" aria-label="Default select example">
                        <option   selected>انتخاب نوع برند</option>

        
                    </select>
                </div>
                <div class="mb-3">
                    <label  for="exampleInputPassword1" class="form-text mb-2">توضیحات</label>
                    <input aria-label="With textarea"  type="text" class="form-control" dir="ltr" placeholder="" name="des" id="des">
                </div>
                <div class="mb-3">
                    <label  for="exampleInputPassword1" class="form-text mb-2">قیمت</label>
                    <input aria-label="With textarea"  type="text" class="form-control" dir="ltr" placeholder="" name="price" id="price">
                </div>
                <div class="mb-3">
                    <label  for="" class="form-text mb-2">عکس</label>
                    <input  type="file" multiple class="form-control" dir="ltr" placeholder="" name="images[]">
                </div>
                
                <div class="form-check" dir="ltr">
                    <input    class="form-check-input mt-1" type="checkbox" value="0" id="check">
                    <label class="form-text " >کالا موجود است</label>
                </div>
              
                  
               
                {% csrf_token %}
                    
                        <div class="mx-auto m-2 col-md-12 text-center" >
                         <button type="submit"  class="col-md-12 btn btn-secondary mb-2">ثبت آگهی</button>
                      
                        
                     
                      
                        <a id="delete" onclick="delete1()" class="col-md-12 btn mb-2 btn-light" href="#">پاک کردن</a>
                        
                       
                      
               
            </form>
        </div>
    
        </div>
    {% endblock %}





{% block script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


<script>

function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var csrftoken = getCookie('csrftoken');

    

function csrfSafeMethod(method) {
// these HTTP methods do not require CSRF protection
return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
beforeSend: function(xhr, settings) {
    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
        xhr.setRequestHeader("X-CSRFToken",csrftoken);
    }
}
});



var selected = document.getElementById('select')

    function ch(){
        var selectElement = document.getElementById('option');
        while(selectElement.hasChildNodes()){
            selectElement.removeChild(selectElement.firstChild);
        }
        selectElement.add(new Option('انتخاب نوع برند'));

        

        $.post('{% url "category:choise" %}',{
            
            value : selected.value,
            
            },function(data){
                console.log(data['status'].length)
                for (var len = 0; len < data['status'].length; len++) {
                selectElement.add(new Option(data['status'][len]));}
                var t = selectElement.add(new Option('افزوذن',iiiiinin));
                
                })
            }
        


        

            
</script>


{% endblock %}

django-project/category/templates/category/cart.html
{% extends 'base.html' %}
{% load static %}

{% load humanize %}
{% block title %}
    category
{% endblock %}

  
  
{% block body %}
<div class="container mt-5">
    <div class="row mt-5">

        <table dir="rtl" class="mt-5 table table-dark table-striped mt-2">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">نام</th>
                <th scope="col">تعداد</th>
                <th scope="col"> قیمت</th>
                <th scope="col"> قیمت کل</th>
                <th scope="col"></th>
        
                
        
        
              </tr>
            </thead>
            <tbody>
                {% for c in cart %}
              <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{c.product.name}} </td>
                <td><input type="number" value="{{c.number}}" data-slug="{{c.product.slug}}" min="1" max="9" aria-selected="false" onchange="sendproduct(this)"></td>
                <td>{{c.product.price|intcomma}}</td>
                <td id="labal{{c.product.id}}"> {{c.total|intcomma}}</td>
                <td><a href="">حدف</a></td>
               
                {% endfor %}
        
              </tr>
              
              <tr>
                <td>قیمت کل</td>
                
                <td colspan="4"></td>
                <td id="lable_total_price">{{cart.get_total|intcomma}}</td>
                
        
        
              </tr>
             
            </tbody>
          </table>
          <a class="btn btn-primary" href="{% url 'category:order'  %}">تایید ادامه و پرداخت</a>





    </div>
</div>




{% endblock %}




{% block script %}


<script src="{% static 'category/js/cart.js'%}"></script>

{% endblock %}

django-project/category/templates/category/cart2.html
{% extends 'base.html' %}
{% load static %}

{% load humanize %}
{% block title %}
    category
{% endblock %}

  
{% block css %}
<link href="{% static 'category/css/cart.css' %}" rel="stylesheet" >

{% endblock %}
{% block body %}
<section class="sec-tbl" >
    <!--for demo wrap-->
    <h1 >سبد خرید شما</h1>
    <div class="tbl-header mt-5">
      <table  cellpadding="0" cellspacing="0" border="0">
        <thead >
          <tr >
            
            <th>نام کالا</th>
            <th>قیمت</th>
            <th>تعداد</th>
            <th> کل </th>
          </tr>
        </thead>
      </table>
    </div>
    <div class="tbl-content">
      <table dir="rtl" cellpadding="0" cellspacing="0" border="0">
        <tbody>
            {% for c in cart %}
          <tr>
            <td>{{c.product.name}}  <strong><a href="#"> حذف</a></strong> </td>
            <td >{{c.product.price|intcomma}}</td>
            <td><input class="form-control number-input" type="number" value="{{c.number}}" data-slug="{{c.product.slug}}" min="1" max="9" aria-selected="false" onchange="sendproduct(this)"></td>
            <td id="labal{{c.product.id}}">{{c.total|intcomma}} </td>
          </tr>
          {% endfor %}
          <tr>
            <td>قیمت کل</td>
            
            <td colspan="2"></td>
            <td id="lable_total_price">{{cart.get_total|intcomma}}</td>
            
    
    
          </tr>
        </tbody>
      </table>

    </div>
    <a  class="btn btn-primary sub" href="{% url 'category:order'  %}">تایید ادامه و پرداخت</a>

  </section>
  <div class="spinner-grow" role="status">
    <span class="visually-hidden">Loading...</span>
  </div>

  
  <!-- follow me template -->
  <div class="made-with-love">
    Made with
    <i>♥</i> by
    <a target="_blank" href="https://codepen.io/nikhil8krishnan">nice biauty</a>
  </div>



{% endblock %}




{% block script %}


<script src="{% static 'category/js/cart.js'%}"></script>

{% endblock %}

django-project/category/templates/category/list_category.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}
    category
{% endblock %}

  
  
{% block body %}



<div style="direction: ltr;  ">
    {% for type in category %}
         <div  dir="ltr" class="btn-group">
            <a href="{% url 'category:search' type.slug %}" class="btn btn-danger ">{{type}}</a>
            <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
           
              <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
             {% for t in type.cbrand.all %}
             
              
              {% endfor %}
            </ul>
          </div>
          {% endfor %}
        </div>
        
        
          
          

 <div class="container">
    <div class="row">
       
    
          
         
         


        <p id="message" class="alert alert-info" hidden ></p>
    {% for product in products %}
        
        <div class="card m-2" style="width: 18rem;">
            
        {% for image in images %}
                {% if image.product == product %}
               
                    <img src="{{image.image.url}}"  class="mt-1 card-img-top" alt="...">
                
                    {% endif %}
        {% endfor %}
            
            
            <div class="card-body">
            <h5 class="card-title text-center">{{product.name}}</h5>
            <p dir="rtl" class="card-text text-center">توضیحات: {{product.des}}</p>
            <p class="card-text text-center"> قیمت:{{product.price|intcomma}}</p>
            <p class="card-text text-center"> :{{product.slug}}</p>
        
        </div>
            <div class="text-center mb-2">
                <a data-slug="{{product.slug}}" data-name="{{product.name}}" onclick="sendproduct(this)" id="name" class="btn btn-primary col-md-9 mb-2">افزودن به سبد خرید</a>

                <a href="{{product.get_absoulut_url}}" class="btn btn-primary col-md-4 ">جزییات</a>
                <a  data-id="{{product.id}}" class="btn btn-primary col-md-5 " data-is_like="{% if request.user in product.like.all %}dislike{% else %}like{% endif %}" onclick="likeproduct(this)">{% if request.user in product.like.all %}دوست ندارم{% else %}‍‍دوست دارم{% endif %}</a>
                <p id="{{product.id}}" class="card-text"> {{product.get_like_user}}</p>
        
            </div>
            
        </div>
        
    
    {% endfor %} 
{% endblock %}
    </div>
</div>


{% block script %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="/static/category/js/list_category.js"></script>

{% endblock %}

django-project/category/templates/category/not_product.html
{% extends 'base.html' %}

{% block title %}
    category
{% endblock %}

{% block css %}
  <link href="/static/category/css/send_order.css" rel="stylesheet" >
{% endblock %}
  
{% block body %}
<div class="container">
    <div class="row">
      <p id="message" class="alert alert-info" hidden ></p>
      {% for productnot in noti_not_view %}
      <table  dir="rtl" class=" mt-2 table table-dark table-striped">
      
          <thead>
            <tr>
              <th scope="col">{{order.user}}</th>
              <th scope="col">نام محصول</th>
              <th scope="col">تعداد</th>
              <th scope="col"> قیمت</th>
              <th scope="col"> قیمت کل</th>
              <th scope="col">  شماره سبد خرید</th>
      
              <th scope="col">
      
                  {% if order.paid %}
                  <h6 style="color: red;" >پرداخت نشده</h6>
                  {% else %}
                  <h6 >پرداخت شده</h6>
      
                  {% endif %}
              </th>
      
              
      
      
            </tr>
          </thead>
          <tbody>
      
              
            
            
              
              
              
              <tr>
              <th scope="row"></th>
      
                
                <td>{{productnot.product.name}} </td>
                <td>{{productnot.number }}</td>
                <td>{{productnot.price}}</td>
                <td>{{productnot.get_cost}}</td>
      
                <td> {{productnot.order.id}}</td>
                <td><a href="">حدف</a></td>
               
      
           
            
            <tr>
              
            
            
              <td>قیمت کل</td>
            
              <td colspan="4"></td>
              <td>{{order.total_price}}</td>
        <td> <input  id="check" data-id="{{productnot.id}}" value="تایید"  onclick="btn_sumbit(this)" class="btn btn-primary" type="button" value="" id="flexCheckDefault">
              
              
              
      
      
            </tr>
           
          
      
          
            
           
          </tbody>
      
        </table>
       
        {% endfor %}
      
<p class="alert alert-primary">تایید شده</p>
{% for productnot in noti_view %}
<table  dir="rtl" class=" mt-2 table table-dark table-striped">

    <thead>
      <tr>
        <th scope="col">{{order.user}}</th>
        <th scope="col">نام محصول</th>
        <th scope="col">تعداد</th>
        <th scope="col"> قیمت</th>
        <th scope="col"> قیمت کل</th>
        <th scope="col">  شماره سبد خرید</th>

        <th scope="col">

            {% if order.paid %}
            <h6 style="color: red;" >پرداخت نشده</h6>
            {% else %}
            <h6 >پرداخت شده</h6>

            {% endif %}
        </th>

        


      </tr>
    </thead>
    <tbody>

        
      
      
        
        
        
        <tr>
        <th scope="row"></th>

          
          <td>{{productnot.product.name}} </td>
          <td>{{productnot.number }}</td>
          <td>{{productnot.price}}</td>
          <td>{{productnot.get_cost}}</td>

          <td> {{productnot.order.id}}</td>
          <td><a href="">حدف</a></td>
         

     
      
      <tr>
        
      
      
        <td>قیمت کل</td>
      
        <td colspan="4"></td>
        <td>{{order.total_price}}</td>
        
        
        


      </tr>
     
    

    
      
     
    </tbody>

  </table>
 
  {% endfor %}


    </div>
</div>




{% endblock %}




{% block script %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="/static/category/js/not_product.js"></script>
{% endblock %}

django-project/category/templates/category/old_orders.html
{% extends 'base.html' %}

{% block title %}
    category
{% endblock %}

  
  
{% block body %}
<div class="container">
    <div class="row">
{% for order in orders %}
       
        <table dir="rtl" class=" mt-2 table table-dark table-striped">

            <thead>
              <tr>
                <th scope="col">{{order.user}}</th>
                <th scope="col">نام محصول</th>
                <th scope="col">تعداد</th>
                <th scope="col"> قیمت</th>
                <th scope="col"> قیمت کل</th>
                <th scope="col">

                    {% if order.paid %}
                    <h6 style="color: red;" >پرداخت نشده</h6>
                    {% else %}
                    <h6 >پرداخت شده</h6>

                    {% endif %}
                </th>
        
                
        
        
              </tr>
            </thead>
            <tbody>
                {% for product in order.oitems.all %}
              <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{product.product.name}} </td>
                <td>{{product.number}}</td>
                <td>{{product.price}}</td>
                <td> {{product.get_cost}}</td>
                <td><a href="">حدف</a></td>
               
                {% endfor %}
        
              </tr>
              
              <tr>
                <td>قیمت کل</td>
              
                <td colspan="3"></td>
                <td>{{order.total_price}}</td>
                <td> <input  id="check" data-id="{{order.id}}" value="0" {% if order.view %}checked  {% endif %} onchange="checkbox(this)" class="form-check-input mt-1" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-text " >تایید</label><input</td>

                
                
        
        
              </tr>
              
             
            </tbody>
          </table>
         
{% endfor %}




    </div>
</div>




{% endblock %}




{% block script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="/static/category/js/send_order.js"></script>
{% endblock %}

django-project/category/templates/category/share.html
    <input dir="ltr" placeholder="search" type="text" class="form-control">
    {% for user in users %}
  <div class="body-share">
    <h5>{{user.username}}</h5>
    <h6>{{user.name}}</h6>
  </div>
  {% endfor %}